// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz3Hd62X0pTPN8CrYjLUuH8YlkKF6StBk',
    appId: '1:963957040939:web:25e3a9d75e6050c533876e',
    messagingSenderId: '963957040939',
    projectId: 'smartchat-a13ae',
    authDomain: 'smartchat-a13ae.firebaseapp.com',
    storageBucket: 'smartchat-a13ae.appspot.com',
    measurementId: 'G-2KRXSH1ZC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACECKNOEIU_Xtxvg8GZUBEbqBHgCvPiOw',
    appId: '1:963957040939:android:efcf25329966bac633876e',
    messagingSenderId: '963957040939',
    projectId: 'smartchat-a13ae',
    storageBucket: 'smartchat-a13ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEn3y6eXyc_bQ0y3yiz9BiAZardBXyuhA',
    appId: '1:963957040939:ios:fe4541cd4a5eba3333876e',
    messagingSenderId: '963957040939',
    projectId: 'smartchat-a13ae',
    storageBucket: 'smartchat-a13ae.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
